// <auto-generated />
using AITL.ApplicatonProcess.ApplicationAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AITL.ApplicatonProcess.ApplicationAPI.Migrations
{
    [DbContext(typeof(EmployeeDetailsContext))]
    partial class EmployeeDetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AITL.ApplicatonProcess.ApplicationAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmpoyeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Hired")
                        .HasColumnType("bit");

                    b.HasKey("EmpoyeeId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
